image: maven:3.9.6-eclipse-temurin-8

# Version variables that are needed. 
variables:
  LANG: "en_GB.UTF-8"
  LC_ALL: "en_GB.UTF-8"

# List of stages for jobs, and their order of execution
stages:
  - check
  - build
  - lint   
  - test
  - deploy

# This job runs in the test stage, which runs first.
check-job:
    stage: check
    script:
        - pwd
        - apt-get update && apt-get install -y git
        - echo "Checking commit message..."
        - bash ./src/pipeline/check_commits.sh
        - echo "Success."

build-job:
    stage: build
    script:
        - echo "Building the project..."
        - pwd
        - apt-get update && apt-get install -y git
        - cd src/train-ticket
        - mvn clean install -DskipTests
        - echo "Build successful."
